apiVersion: v1
kind: LimitRange
metadata:
  name: customrange
spec:
  limits:
  - type: Container
    default:
      memory: 50Mi
      cpu: 150m
    defaultRequest:
      memory: 10Mi
      cpu: 10m
    max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 10Mi
      cpu: 1m
