apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumetest
  labels:
    app: volumetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumetestpods
  template:
    metadata:
      labels:
        app: volumetestpods
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
      - name: worker
        image: busybox:latest
        volumeMounts:
        - name: html
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              date >> /html/index.html;
              sleep 10;
            done
      volumes:
      - name: html
        emptyDir: {}