apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamicclaim
spec:
  accessModes:
    - ReadWriteOnce # Volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard # If omitted, will use the default storage class