apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplevolume
  labels:
    app: simplevolume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplevolumepod
  template:
    metadata:
      labels:
        app: simplevolumepod
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "while true; do ls /tmp/storage; sleep 10; done"]
        volumeMounts:
        - mountPath: /tmp/storage
          name: my-volume
      volumes:
      - name: my-volume
        emptyDir: {}