apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplevolume
  labels:
    app: simplevolume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplevolumepod
  template:
    metadata:
      labels:
        app: simplevolumepod
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
        volumeMounts:
        - mountPath: /tmp/data
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: dynamicclaim