apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejsapp
  labels:
    app: mynodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynodejsapp
  template:
    metadata:
      labels:
        app: mynodejsapp
    spec:
      volumes:
        - name: configmap-json
          configMap:
            # Provide the name of the ConfigMap containing the files you want to add to the container
            name: myapp-cm2
      containers:
      - name: mynodejsapp
        image: mynodejsapp:5.0
        ports:
        - containerPort: 8080 #which port is exposed OUTSIDE the container
        volumeMounts:
          - name: configmap-json
            mountPath: /config
        env:
          - name: SITE_COLOR
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: myapp-cm1
                # Specify the key associated with the value
                key: color
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: myapp-secret1
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secret1
                key: password