apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: 500Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 50m
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "10"]
    