apiVersion: v1
kind: Service
metadata:
  name: italy
  namespace: default
spec:
  type: NodePort
  selector:
    app: italy #does this need to be modified?
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
