apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: default
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue #Pull correct image tag
    imagePullPolicy: IfNotPresent
    name: kuard
    resources: {}
  restartPolicy: Never
  serviceAccount: default
