apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx_web
        app.kubernetes.io/managed-by: ops
        app.kubernetes.io/env: dev
        app.kubernetes.io/release: test
      annotations:
        git_repo: "https://github.com/java/world"
        owner: "John Smith 0123456789"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80 #which port is exposed OUTSIDE the container